// Acceptance test for issue #13's A+ fix: Matrix.exp() must match Giac (the
// black-box reference for calculatrix) to a relative Frobenius error of
// 1e-12 or better, on a fixed catalog of fixtures.
//
// This replaces the earlier "never less precise than main" criterion: the
// reference is now an independent computer algebra system (Giac), not this
// project's own previous behavior.
//
// The fixture file (test/fixtures/matrix_exp_giac_reference.json) is
// generated by tool/giac/generate_fixtures.py, which shells out to Giac via
// WSL and records a 30-digit decimal reference per case. This test only
// reads that committed JSON: it never calls Giac itself, so CI does not
// need Giac or WSL installed.
//
// The catalog is every case from the exploration catalog (scratchpad
// cases.py) except two matrices filed as separate GitHub issues (a
// nonFinite case whose true result is representable, and a subnormal-range
// case at the double precision limit), plus four new cases added for this
// fix: x10-scaled versions of the I+N, diag(I+N,2) and Jordan 5I+N cases
// (exercising exact-nilpotent detection at larger magnitude), and a 4x4
// matrix with two independent Jordan-type blocks interleaved by a
// permutation (exercising connected-component detection).

import 'dart:convert';
import 'dart:io';
import 'dart:math' as math;

import 'package:calculatrix/calculatrix.dart';
import 'package:test/test.dart';

void main() {
  final File fixtureFile = File('test/fixtures/matrix_exp_giac_reference.json');

  group('Matrix.exp - matches Giac to 1e-12 relative Frobenius error '
      '(issue #13, A+ acceptance criterion)', () {
    test('fixture file exists and has at least 18 cases', () {
      expect(
        fixtureFile.existsSync(),
        isTrue,
        reason: 'run tool/giac/generate_fixtures.py to (re)generate it',
      );
      final List<dynamic> cases =
          jsonDecode(fixtureFile.readAsStringSync()) as List<dynamic>;
      expect(cases.length, greaterThanOrEqualTo(18));
    });

    final List<dynamic> cases =
        jsonDecode(fixtureFile.readAsStringSync()) as List<dynamic>;

    for (final dynamic rawCase in cases) {
      final Map<String, dynamic> fixture = rawCase as Map<String, dynamic>;
      final String name = fixture['name'] as String;
      final List<List<double>> matrixRows = _toDoubleRowsFromNumbers(
        fixture['matrix'] as List<dynamic>,
      );
      final List<List<double>> referenceRows = _toDoubleRowsFromStrings(
        fixture['reference'] as List<dynamic>,
      );

      test('$name', () {
        final Matrix matrix = Matrix(matrixRows);
        final Matrix actual = matrix.exp();
        final Matrix reference = Matrix(referenceRows);

        final double relativeError = _relativeFrobeniusError(actual, reference);
        expect(
          relativeError,
          lessThanOrEqualTo(1e-12),
          reason:
              'expected (Giac) $reference, got $actual '
              '(relative Frobenius error $relativeError)',
        );
      });
    }
  });
}

List<List<double>> _toDoubleRowsFromNumbers(List<dynamic> rows) {
  return [
    for (final dynamic row in rows)
      [
        for (final dynamic value in row as List<dynamic>)
          (value as num).toDouble(),
      ],
  ];
}

List<List<double>> _toDoubleRowsFromStrings(List<dynamic> rows) {
  return [
    for (final dynamic row in rows)
      [
        for (final dynamic value in row as List<dynamic>)
          double.parse(value as String),
      ],
  ];
}

double _relativeFrobeniusError(Matrix actual, Matrix expected) {
  double diffSquaredSum = 0;
  double expectedSquaredSum = 0;
  for (int row = 0; row < expected.rowCount; row++) {
    for (int column = 0; column < expected.columnCount; column++) {
      final double diff = actual.at(row, column) - expected.at(row, column);
      diffSquaredSum += diff * diff;
      final double expectedValue = expected.at(row, column);
      expectedSquaredSum += expectedValue * expectedValue;
    }
  }
  final double diffNorm = math.sqrt(diffSquaredSum);
  final double expectedNorm = math.sqrt(expectedSquaredSum);
  if (expectedNorm == 0) {
    return diffNorm == 0 ? 0 : diffNorm;
  }
  return diffNorm / expectedNorm;
}
