// Acceptance test for issue #19: Matrix.sqrt() must return the real
// principal square root of a singular matrix whose zero eigenvalue is
// semisimple (diagonalizable) and that has no negative real eigenvalues,
// instead of rejecting every singular input outright.
//
// Reference: Giac (the black-box reference for calculatrix), not Julia or
// numpy. The fixture file
// (test/fixtures/matrix_sqrt_singular_giac_reference.json) is generated by
// tool/giac/generate_sqrt_fixtures.py, which shells out to Giac via WSL and
// records a 30-digit decimal `matpow(<matrix>, 1/2)` reference per case.
// This test only reads that committed JSON: it never calls Giac itself, so
// CI does not need Giac or WSL installed.
//
// A singular matrix with no real square root at all (the zero eigenvalue is
// not semisimple, e.g. a nilpotent Jordan block) must keep raising
// MatrixDomainError with a wrong-domain message, never a numeric matrix.
// Giac itself confirms this for the nilpotent case: `matpow([[0,1],[0,0]],
// 1/2)` -> "Unable to transpose Error: Bad Argument Value" (no real
// principal square root exists), which is why that case has no numeric
// fixture entry.
import 'dart:convert';
import 'dart:io';
import 'dart:math' as math;

import 'package:calculatrix/calculatrix.dart';
import 'package:test/test.dart';

void main() {
  final File fixtureFile = File(
    'test/fixtures/matrix_sqrt_singular_giac_reference.json',
  );

  group('Matrix.sqrt() on singular matrices - matches Giac to 1e-12 relative '
      'Frobenius error (issue #19 acceptance criterion)', () {
    test('fixture file exists and has at least 3 cases', () {
      expect(
        fixtureFile.existsSync(),
        isTrue,
        reason: 'run tool/giac/generate_sqrt_fixtures.py to (re)generate it',
      );
      final List<dynamic> cases =
          jsonDecode(fixtureFile.readAsStringSync()) as List<dynamic>;
      expect(cases.length, greaterThanOrEqualTo(3));
    });

    final List<dynamic> cases =
        jsonDecode(fixtureFile.readAsStringSync()) as List<dynamic>;

    for (final dynamic rawCase in cases) {
      final Map<String, dynamic> fixture = rawCase as Map<String, dynamic>;
      final String name = fixture['name'] as String;
      final String giacExpr = fixture['giacExpr'] as String;
      final List<List<double>> matrixRows = _toDoubleRowsFromNumbers(
        fixture['matrix'] as List<dynamic>,
      );
      final List<List<double>> referenceRows = _toDoubleRowsFromStrings(
        fixture['reference'] as List<dynamic>,
      );

      test('$name (Giac: $giacExpr)', () {
        final Matrix matrix = Matrix(matrixRows);
        final Matrix actual = matrix.sqrt();
        final Matrix reference = Matrix(referenceRows);

        final double relativeError = _relativeFrobeniusError(actual, reference);
        expect(
          relativeError,
          lessThanOrEqualTo(1e-12),
          reason:
              'expected (Giac $giacExpr) $reference, got $actual '
              '(relative Frobenius error $relativeError)',
        );

        // Every returned root must square back to the original matrix.
        final Matrix squared = actual * actual;
        final double reconstructionError = _relativeFrobeniusError(
          squared,
          matrix,
        );
        expect(
          reconstructionError,
          lessThanOrEqualTo(1e-9),
          reason:
              'X*X should reconstruct the original matrix $matrix, '
              'got $squared (relative Frobenius error $reconstructionError)',
        );
      });
    }
  });

  group('Matrix.sqrt() on singular matrices with no real square root '
      '(issue #19)', () {
    test('raises MatrixDomainError for a nilpotent Jordan block '
        '(Giac: matpow([[0,1],[0,0]],1/2) -> "Unable to transpose Error: '
        'Bad Argument Value")', () {
      final Matrix value = Matrix(<List<double>>[
        <double>[0, 1],
        <double>[0, 0],
      ]);

      expect(() => value.sqrt(), throwsA(isA<MatrixDomainError>()));
    });

    test('raises MatrixDomainError for a singular matrix whose zero '
        'eigenvalue is not semisimple, even scaled (3x3 Jordan block, '
        'eigenvalue 0 with algebraic multiplicity 3 and geometric '
        'multiplicity 1)', () {
      final Matrix value = Matrix(<List<double>>[
        <double>[0, 1, 0],
        <double>[0, 0, 1],
        <double>[0, 0, 0],
      ]);

      expect(() => value.sqrt(), throwsA(isA<MatrixDomainError>()));
    });
  });
}

List<List<double>> _toDoubleRowsFromNumbers(List<dynamic> rows) {
  return [
    for (final dynamic row in rows)
      [
        for (final dynamic value in row as List<dynamic>)
          (value as num).toDouble(),
      ],
  ];
}

List<List<double>> _toDoubleRowsFromStrings(List<dynamic> rows) {
  return [
    for (final dynamic row in rows)
      [
        for (final dynamic value in row as List<dynamic>)
          double.parse(value as String),
      ],
  ];
}

double _relativeFrobeniusError(Matrix actual, Matrix expected) {
  double diffSquaredSum = 0;
  double expectedSquaredSum = 0;
  for (int row = 0; row < expected.rowCount; row++) {
    for (int column = 0; column < expected.columnCount; column++) {
      final double diff = actual.at(row, column) - expected.at(row, column);
      diffSquaredSum += diff * diff;
      final double expectedValue = expected.at(row, column);
      expectedSquaredSum += expectedValue * expectedValue;
    }
  }
  final double diffNorm = math.sqrt(diffSquaredSum);
  final double expectedNorm = math.sqrt(expectedSquaredSum);
  if (expectedNorm == 0) {
    return diffNorm == 0 ? 0 : diffNorm;
  }
  return diffNorm / expectedNorm;
}
