name: calculatrix_cli
description: Command-line interface for Calculatrix.
version: 3.1.0
publish_to: 'none'

environment:
  sdk: ^3.8.1

dependencies:
  calculatrix:
    path: ../core

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
